Repository Mogazoa-team20/mogazoa, pull requests merged in 2024-06, with the labels that each got.

#39 auth 레이아웃 적용 + 공통 레이아웃 스타일 추가
  src/app/(auth)/AuthLayout.module.scss
  src/app/(auth)/layout.tsx
  src/app/RootLayout.module.scss
  src/app/layout.tsx
Labels: 📜 Page

#40 홈 화면 ui 구현
  src/app/_home/components/Category/Category/Category.module.scss
  src/app/_home/components/Category/Category/Category.tsx
  src/app/_home/components/Category/Category/index.ts
  src/app/_home/components/Category/CategoryList/CategoryList.module.scss
  src/app/_home/components/Category/CategoryList/CategoryList.tsx
  src/app/_home/components/Category/CategoryList/index.ts
  src/app/_home/components/Category/index.ts
  src/app/_home/components/Main/Main.module.scss
  src/app/_home/components/Main/Main.tsx
  src/app/_home/components/Main/index.ts
  src/app/_home/components/Products/FilteredProducts/FilteredProducts.module.scss
  src/app/_home/components/Products/FilteredProducts/FilteredProducts.tsx
  src/app/_home/components/Products/FilteredProducts/index.ts
  src/app/_home/components/Products/PopularProducts/PopularProducts.module.scss
  src/app/_home/components/Products/PopularProducts/PopularProducts.tsx
  src/app/_home/components/Products/PopularProducts/index.ts
  src/app/_home/components/Products/ProductList/ProductList.module.scss
  src/app/_home/components/Products/ProductList/ProductList.tsx
  src/app/_home/components/Products/ProductList/index.ts
  src/app/_home/components/Products/index.ts
  src/app/_home/components/ReviewerRanking/ReviewerRanking.module.scss
  src/app/_home/components/ReviewerRanking/ReviewerRanking.tsx
  src/app/_home/components/ReviewerRanking/index.ts
  src/app/_home/constants.ts
  src/app/_home/mock.ts
  src/app/_home/types.ts
  src/app/page.module.scss
  src/app/page.tsx
  src/components/Chip/Ranking/Ranking.tsx
  src/components/Gnb/Gnb.module.scss
  src/components/Gnb/Gnb.tsx
  src/components/Gnb/SearchInput/SearchInput.tsx
  src/components/ProductCard/ProductCard.module.scss
  src/components/ProductCard/ProductCard.tsx
  src/components/ProductCard/index.ts
  src/components/UserItem/UserItem.module.scss
  src/types/global.ts
  src/utils/createQueryString.ts
  tsconfig.json
Labels: 📜 Page

#37 비교하기 페이지 구현
  src/app/compare/compare.module.scss
  src/app/compare/page.tsx
  src/components/Button/Button.module.scss
  src/components/Card/Activity/Activity.module.scss
  src/components/Card/Statistics/Statistics.module.scss
  src/components/Chip/Category-filter/CategoryFilter.module.scss
  src/components/Chip/Category/Category.module.scss
  src/components/Chip/Compare/Compare.module.scss
  src/components/Chip/Compare/Compare.tsx
  src/components/Chip/Ranking/Ranking.module.scss
  src/components/Chip/Thumbs/Thumbs.module.scss
Labels: ✨ Feature, 📜 Page

#42 [#41] 임시 로그인페이지 생성
  package.json
  src/app/(auth)/AuthLayout.module.scss
  src/app/(auth)/signin/SignInPage.module.scss
  src/app/(auth)/signin/page.tsx
  src/app/_home/components/Main/Main.module.scss
  src/app/api/auth/[...nextauth]/route.ts
  src/app/layout.tsx
  src/lib/AuthProvider.tsx
  src/types/auth.d.ts
Labels: 📜 Page

#31 [#17] Input 컴포넌트 구현
  .eslintrc.json
  src/components/Input/Input.module.scss
  src/components/Input/Input.tsx
  src/utils/constant.ts
Labels: ✨ Component

#47 홈화면 api 요청
  next.config.mjs
  src/app/_home/api/getData.ts
  src/app/_home/components/Main/Main.tsx
  src/app/_home/components/Products/FilteredProducts/FilteredProducts.tsx
  src/app/_home/components/Products/PopularProducts/PopularProducts.tsx
  src/app/_home/components/Products/ProductList/ProductList.tsx
  src/app/_home/hooks/useGetFilteredProducts.ts
  src/app/_home/hooks/useQueryParams.ts
  src/app/_home/mock.ts
  src/app/error.tsx
  src/app/page.tsx
  src/components/Chip/Ranking/Ranking.module.scss
  src/types/global.ts
Labels: ✨ Feature, 📜 Page

#50 드롭다운 및 홈화면 UI 버그 수정
  src/app/_home/components/Main/Main.tsx
  src/components/Dropdown/Dropdown.module.scss
  src/components/Gnb/SearchInput/SearchInput.tsx
Labels: 🐞 BugFix

#49 fix: UserItem 팔로워, 리뷰수 0일 경우 나타나지 않는 오류 수정 + 닉네임 글자 수 제한 추가
  src/components/UserItem/UserItem.tsx
Labels: 🐞 BugFix, ✨ Component

#53 fix: authOptions 코드 route에서 분리
  src/app/api/auth/[...nextauth]/route.ts
  src/lib/auth.ts
Labels: 🐞 BugFix

#51 feat: 비교하기 페이지 구현
  .env
  src/app/compare/compare.module.scss
  src/app/compare/input/CompareInput.module.scss
  src/app/compare/input/CompareInput.tsx
  src/app/compare/input/compareProductMock.ts
  src/app/compare/input/localStorage.ts
  src/app/compare/page.tsx
  src/app/compare/table/CompareTable.module.scss
  src/app/compare/table/CompareTable.tsx
Labels: ✨ Feature, 📜 Page

#64 [#27] 간편 로그인 컴포넌트&로직
  src/app/(auth)/oauth/signup/[provider]/page.tsx
  src/app/(auth)/signin/_components/OauthSignInBox/OauthSignInBox.module.scss
  src/app/(auth)/signin/_components/OauthSignInBox/OauthSignInBox.tsx
  src/app/(auth)/signin/_components/OauthSignInBox/index.ts
  src/app/(auth)/signin/_components/OauthSignInButton/OauthSignInButton.module.scss
  src/app/(auth)/signin/_components/OauthSignInButton/OauthSignInButton.tsx
  src/app/(auth)/signin/_components/OauthSignInButton/index.ts
  src/app/(auth)/signin/page.tsx
  src/app/layout.tsx
  src/lib/auth.ts
  src/types/auth.d.ts
  tsconfig.json
Labels: ✨ Feature, ✨ Component

#67 [#34, #41] feat: signin form 컴포넌트/로직
  src/app/(auth)/constants.ts
  src/app/(auth)/signin/SignInPage.module.scss
  src/app/(auth)/signin/_components/SignInForm/SignInForm.module.scss
  src/app/(auth)/signin/_components/SignInForm/SignInForm.tsx
  src/app/(auth)/signin/_components/SignInForm/index.ts
  src/app/(auth)/signin/page.tsx
  src/lib/auth.ts
  src/styles/_common.scss
Labels: ✨ Feature, ✨ Component, 📜 Page

#69 [#65] 회원가입 폼/로직, 에러 안내 모달 컴포넌트 구현
  src/app/(auth)/_components/AlertModal/AlertModal.module.scss
  src/app/(auth)/_components/AlertModal/AlertModal.tsx
  src/app/(auth)/_components/AlertModal/index.ts
  src/app/(auth)/signup/_components/SignUpForm/SignUpForm.module.scss
  src/app/(auth)/signup/_components/SignUpForm/SignUpForm.tsx
  src/app/(auth)/signup/_components/SignUpForm/index.ts
  src/app/(auth)/signup/page.tsx
  src/lib/auth.ts
Labels: ✨ Feature, ✨ Component, 📜 Page

#68 Home httpClient 클래스 사용
  src/app/_home/api/getData.ts
  src/app/_home/components/Category/CategoryList/CategoryList.tsx
  src/app/_home/components/Main/Main.tsx
  src/app/_home/types.ts
  src/app/layout.tsx
  src/app/page.tsx
  src/types/global.ts
Labels: 🔨 Refactor

#71 [#70] feat: 페이지 접근 권한 관리 middleware 파일 생성
  src/lib/auth.ts
  src/middleware.ts
Labels: ✨ Feature

#77 fix: next auth credentials id 불일치 수정
  src/app/(auth)/oauth/signup/[provider]/page.tsx
  src/app/(auth)/signin/_components/SignInForm/SignInForm.tsx
  src/lib/auth.ts
Labels: 🐞 BugFix

#75 Feat/compare page
  src/app/compare/input/CompareInput.module.scss
  src/app/compare/input/CompareInput.tsx
  src/app/compare/input/compareProductItem.ts
  src/app/compare/input/compareProductMock.ts
  src/app/compare/page.tsx
  src/app/compare/table/CompareTable.tsx
Labels: ✨ Feature, 📜 Page

#80 상품 추가 모달
  src/app/layout.tsx
  src/components/AddModal/AddModal.module.scss
  src/components/AddModal/AddModal.tsx
  src/components/AddModal/index.ts
  src/components/FloatingButton/FloatingButton.module.scss
  src/components/FloatingButton/FloatingButton.tsx
  src/components/FloatingButton/index.ts
  src/components/Gnb/Gnb.tsx
  src/hooks/useGetCategory.ts
  src/hooks/useSessionCheck.ts
  src/hooks/useUpdateProduct.ts
  src/types/global.ts
Labels: ✨ Feature, ✨ Component, 📜 Page

#84 refactor: 상품 리스트 suspense 추가
  src/app/_home/components/Main/Main.tsx
  src/app/_home/components/Products/FilteredProducts/FilteredProducts.tsx
  src/app/_home/hooks/useGetFilteredProducts.ts
  src/components/ErrorBoundary/ErrorBoundary.tsx
  src/components/ErrorBoundary/index.ts
  src/components/NoData/NoData.module.scss
  src/components/NoData/NoData.tsx
  src/components/NoData/index.ts
Labels: 🔨 Refactor

#87 [#83] fix: 레이아웃 width 관련 오류 수정, 스크롤바 디자인 추가
  src/app/RootLayout.module.scss
  src/app/compare/input/CompareInput.module.scss
  src/styles/_common.scss
Labels: 📜 Page

#89 [#35] 유저페이지 접속 시 모든요청이 마이페이지로 가는 에러 수정
  src/app/(userpage)/user/[userId]/components/UserActivityList/UserActivityList.tsx
  src/app/(userpage)/user/[userId]/page.tsx
Labels: 🐞 BugFix, 🔨 Refactor, 📜 Page

#91 [#88] not-found 페이지 추가, error 페이지 디자인 추가
  src/app/commonErrorStyle.scss
  src/app/error.tsx
  src/app/not-found.tsx
Labels: 📜 Page

#90 Product Card 컴포넌트 스타일 추가 및 수정
  src/components/ProductCard/ProductCard.module.scss
Labels: 🔨 Refactor, ✨ Component

#93 Gnb, Ranking 스타일
  src/app/_home/components/Main/Main.module.scss
  src/app/_home/components/Main/Main.tsx
  src/app/_home/components/ReviewerRanking/ReviewerRanking.module.scss
  src/components/Gnb/Gnb.module.scss
  src/components/Gnb/Gnb.tsx
Labels: 🔨 Refactor

#95 [#94] fix: 간편 로그인 로직 에러 수정
  src/app/(auth)/_components/OauthSignInBox/OauthSignInBox.tsx
  src/app/(auth)/signin/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/layout.tsx
  src/lib/auth.ts
Labels: 🐞 BugFix

#96 fix: 홈 스타일 수정
  src/app/_home/components/Main/Main.module.scss
  src/app/_home/components/ReviewerRanking/ReviewerRanking.module.scss
Labels: 📜 Page

#100 Button, ActivityCard 공통컴포넌트수정
  src/components/Button/Button.module.scss
  src/components/Card/Activity/Activity.tsx
Labels: 🐞 BugFix, ✨ Component

#102 팔로우 버튼 정상 작동 및 잡다한 내용 수정
  src/app/(userpage)/user/[userId]/components/FollowModal/FollowModal.tsx
  src/app/(userpage)/user/[userId]/components/MyProfileButton/MyProfileButton.module.scss
  src/app/(userpage)/user/[userId]/components/MyProfileButton/MyProfileButton.tsx
  src/app/(userpage)/user/[userId]/components/UserActivityList/UserActivityList.tsx
  src/app/(userpage)/user/[userId]/components/UserInfo/UserInfo.module.scss
  src/app/(userpage)/user/[userId]/components/UserInfo/UserInfo.tsx
  src/app/(userpage)/user/[userId]/page.tsx
  src/components/Card/Activity/Activity.tsx
  src/types/global.ts
Labels: 🐞 BugFix, ✨ Component, 📜 Page

#106 design: Shopping 컴포넌트 스타일 수정
  public/images/coupang.svg
  public/images/naver.svg
  src/app/product/components/card/CoupangCard.module.scss
  src/app/product/components/card/CoupangCard.tsx
  src/app/product/components/card/NaverCard.module.scss
  src/app/product/components/card/NaverCard.tsx
  src/app/product/components/shopping/Shopping.module.scss
  src/app/product/components/shopping/Shopping.tsx
  src/components/Button/Button.module.scss
  src/utils/constant.ts
Labels: ✨ Component

#107 프로필 수정 기능구현 및 팔로우 팔로워 데이터 수정
  src/app/(userpage)/user/[userId]/components/FollowList/FollowList.tsx
  src/app/(userpage)/user/[userId]/components/FollowModal/FollowModal.tsx
  src/app/(userpage)/user/[userId]/components/FolloweeList/FolloweeList.module.scss
  src/app/(userpage)/user/[userId]/components/FolloweeList/FolloweeList.tsx
  src/app/(userpage)/user/[userId]/components/FollowerList/FollowerList.module.scss
  src/app/(userpage)/user/[userId]/components/FollowerList/FollowerList.tsx
  src/app/(userpage)/user/[userId]/components/MyProfileButton/MyProfileButton.module.scss
  src/app/(userpage)/user/[userId]/components/MyProfileButton/MyProfileButton.tsx
  src/app/(userpage)/user/[userId]/components/UserInfo/UserInfo.tsx
  src/app/(userpage)/user/[userId]/hooks/useGetFollow.ts
  src/app/(userpage)/user/[userId]/hooks/useUpdateProfile.ts
  src/types/global.ts
Labels: 🐞 BugFix, ✨ Feature, ✨ Component

#109 refactor: 카카오 스크립트 관련 수정
  src/app/(auth)/_components/OauthSignInBox/OauthSignInBox.tsx
  src/app/layout.tsx
  src/app/product/utils/kakao.ts
  src/lib/KakaoScript.tsx
  src/types/auth.d.ts
Labels: 🔨 Refactor

#112 fix: 사파리에서 pretendard 글꼴로 나타나지 않는 문제 수정
  src/app/layout.tsx
  src/styles/_common.scss
Labels: 🐞 BugFix

#113 fix: 별점 소수점 설정
  src/components/ProductCard/ProductCard.tsx
Labels: 🐞 BugFix

#114 design: Shopping/NaverCard/CoupangCard 반응형 디자인 적용
  src/app/product/components/card/CoupangCard.module.scss
  src/app/product/components/card/NaverCard.module.scss
  src/app/product/components/shopping/Shopping.module.scss
Labels: ✨ Component

#116 [#115] feat: 토스트 컴포넌트 구현
  package-lock.json
  package.json
  public/images/caution.svg
  public/images/error.svg
  public/images/info.svg
  public/images/success.svg
  src/app/layout.tsx
  src/app/product/components/card/CoupangCard.module.scss
  src/app/product/components/card/NaverCard.module.scss
  src/app/product/components/shopping/Shopping.module.scss
  src/components/ProductCard/ProductCard.module.scss
  src/components/Toast/Toast.tsx
  src/components/Toast/ToastBox/ToastBox.module.scss
  src/components/Toast/ToastBox/ToastBox.tsx
  src/components/Toast/ToastBox/index.ts
  src/components/Toast/ToastList/ToastList.module.scss
  src/components/Toast/ToastList/ToastList.tsx
  src/components/Toast/ToastList/index.ts
  src/components/Toast/index.ts
  src/components/Toast/type.ts
  src/styles/_common.scss
  src/utils/constant.ts
Labels: ✨ Feature, ✨ Component

#118 fix: statistic Card 별점 평균 외 나머지 소수점 제거 (#22)
  src/components/Card/Statistics/Statistics.tsx
Labels: 🐞 BugFix

#119 fix: Toast 관련 오류 수정 + auth 페이지 수정(toast 사용)
  src/app/(auth)/_components/OauthSignInBox/OauthSignInBox.tsx
  src/app/(auth)/oauth/signup/[provider]/_components/OauthSignUpForm/OauthSignUpForm.tsx
  src/app/(auth)/signin/_components/SignInForm/SignInForm.tsx
  src/app/(auth)/signup/_components/SignUpForm/SignUpForm.tsx
  src/components/Toast/Toast.tsx
  src/components/Toast/ToastBox/ToastBox.module.scss
Labels: 🐞 BugFix, ✨ Feature, ✨ Component

#130 fix: 간편 로그인 후 accessToken이 제대로 연결되지 않는 문제 수정
  src/lib/auth.ts
Labels: 🐞 BugFix

#135 feature: auth 로직 이후 성공시 redirect 경로 분기 추가
  src/app/(auth)/oauth/signup/[provider]/_components/OauthSignUpForm/OauthSignUpForm.tsx
  src/app/(auth)/signin/_components/SignInForm/SignInForm.tsx
  src/app/(auth)/signup/_components/SignUpForm/SignUpForm.tsx
  src/utils/session.ts
Labels: ✨ Feature

#137 fix:
  src/utils/session.ts
Labels: 🐞 BugFix

#150 fix: 리뷰수정모달 스크롤 비가시화, 클립보드 복사 토스트 추가
  src/app/product/components/modal/ReviewEditModal.module.scss
  src/app/product/utils/share.ts
Labels: 🐞 BugFix

#151 fix: 누락됐던 리뷰 모달 스타일 추가 수정
  src/app/product/components/modal/ReviewModal.module.scss
Labels: 🐞 BugFix

#162 fix: 로그인 요청 후 페이지 이동 관련 추가 수정
  src/app/(auth)/_components/OauthSignInBox/OauthSignInBox.tsx
  src/app/(auth)/oauth/signup/[provider]/_components/OauthSignUpForm/OauthSignUpForm.tsx
  src/app/(auth)/signin/_components/SignInForm/SignInForm.tsx
  src/app/(auth)/signup/_components/SignUpForm/SignUpForm.tsx
Labels: 🐞 BugFix

#164 feat: 동적 메타데이터 추가
  public/images/opengraph.png
  src/app/(auth)/oauth/signup/[provider]/page.tsx
  src/app/(auth)/signin/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/layout.tsx
  src/app/product/[slug]/page.tsx
  src/utils/constant.ts
  src/utils/metadata.ts
Labels: ✨ Feature

#170 refactor: auth.ts 파일 내부의 공통 로직 분리
  src/app/(auth)/_utils/getAuth.ts
  src/lib/auth.ts
Labels: 🔨 Refactor

#171 feat: 토스트 개수 제한 추가
  src/components/Toast/Toast.tsx
Labels: ✨ Feature
